# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration
client_id = "ff83393da1801e09eff3d5c5c04bbc85"
application_url = "https://stripes-specials-physics-fred.trycloudflare.com"  # or leave blank; CLI will set on dev
embedded = true

name = "wishlist-explorer"
handle = "wishlist-explorer"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "carttransformer.myshopify.com"

[access_scopes]
scopes = "read_products,write_products,write_files,read_customers,write_customers"

[webhooks]
api_version = "2024-07"   # use stable for the checker

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request","customers/redact","shop/redact"]
uri = "https://stripes-specials-physics-fred.trycloudflare.com/webhooks/compliance"  # absolute

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "https://stripes-specials-physics-fred.trycloudflare.com/webhooks/app/uninstalled"

[auth]
redirect_urls = ["https://stripes-specials-physics-fred.trycloudflare.com/auth/callback","https://stripes-specials-physics-fred.trycloudflare.com/auth/shopify/callback","https://stripes-specials-physics-fred.trycloudflare.com/api/auth/callback"]

